<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Parallel test suite" duration-ms="70950" started-at="2019-04-15T11:21:13Z" finished-at="2019-04-15T11:22:23Z">
    <groups>
    </groups>
    <test name="test" duration-ms="70950" started-at="2019-04-15T11:21:13Z" finished-at="2019-04-15T11:22:23Z">
      <class name="com.tc.TestCase">
        <test-method status="PASS" signature="beforeClass(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.tc.TestCase@3dd3bcd]" name="beforeClass" is-config="true" duration-ms="47661" started-at="2019-04-15T11:21:13Z" finished-at="2019-04-15T11:22:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[http://202.131.117.92:7023/#/login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="Testcase11(java.lang.reflect.Method)[pri:11, instance:com.tc.TestCase@3dd3bcd]" name="Testcase11" duration-ms="1327" started-at="2019-04-15T11:22:00Z" description="TC-11 | Enter valid email and valid password | Login Test case" finished-at="2019-04-15T11:22:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tc.TestCase.Testcase11(java.lang.reflect.Method) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase11 -->
        <test-method status="SKIP" signature="Testcase18(java.lang.reflect.Method)[pri:18, instance:com.tc.TestCase@3dd3bcd]" name="Testcase18" duration-ms="20373" started-at="2019-04-15T11:22:02Z" description="TC-18 | Click on any one project | Dashboard screen &gt; Project" finished-at="2019-04-15T11:22:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tc.TestCase.Testcase18(java.lang.reflect.Method) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.tc.TestCase.Testcase18(TestCase.java:278)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase18 -->
        <test-method status="FAIL" signature="Testcase18(java.lang.reflect.Method)[pri:18, instance:com.tc.TestCase@3dd3bcd]" name="Testcase18" duration-ms="1" started-at="2019-04-15T11:22:22Z" description="TC-18 | Click on any one project | Dashboard screen &gt; Project" finished-at="2019-04-15T11:22:22Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase18 -->
        <test-method status="PASS" signature="Testcase19(java.lang.reflect.Method)[pri:19, instance:com.tc.TestCase@3dd3bcd]" name="Testcase19" duration-ms="32" started-at="2019-04-15T11:22:23Z" description="TC-19 | Verify there is any screens or folder are available or not | Project details screen" finished-at="2019-04-15T11:22:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tc.TestCase.Testcase19(java.lang.reflect.Method) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase19 -->
        <test-method status="PASS" signature="Testcase20(java.lang.reflect.Method)[pri:20, instance:com.tc.TestCase@3dd3bcd]" name="Testcase20" duration-ms="83" started-at="2019-04-15T11:22:23Z" description="TC-20 | Click on new folder button and verify popup is looking or not | Project details screen" finished-at="2019-04-15T11:22:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.tc.TestCase.Testcase20(java.lang.reflect.Method) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase20 -->
        <test-method status="PASS" signature="down()[pri:0, instance:com.tc.TestCase@3dd3bcd]" name="down" is-config="true" duration-ms="674" started-at="2019-04-15T11:22:23Z" finished-at="2019-04-15T11:22:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- down -->
      </class> <!-- com.tc.TestCase -->
    </test> <!-- test -->
  </suite> <!-- Parallel test suite -->
</testng-results>
